[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16mb.csv
board_build.arduino.memory_type = qio_opi
Board_upload.flash_size = 16MB

lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/mobizt/ESP-Mail-Client.git
    bluetoothserial
    preferences
    bblanchon/ArduinoJson@^6.21.4
    adafruit/Adafruit Neopixel

build_flags = 
    -DBOARD_HAS_PSRAM
    -DUSER_SETUP_LOADED
    -DILI9488_DRIVER
    -DTFT_WIDTH=480
    -DTFT_HEIGHT=320
    -DTFT_CS=5
    -DTFT_DC=17
    -DTFT_RST=16
    -DTFT_BL=4
    -DTFT_BACKLIGHT_ON_HIGH=1
    -DTOUCH_DRIVER=GT911
    -DTOUCH_SDA=15
    -DTOUCH_SCL=7
    -DTOUCH_RST=16
    -DTOUCH_INT=17
    -DTOUCH_CS=-1              ; Explicitly disable CS (required for I2C touch)
    ; -DBUZZER_PIN=12          ; Passive buzzer GPIO – set when known, e.g. 12
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000

lib_ignore = WebServer