#!/usr/bin/env python3
"""
Read a 24-bit uncompressed BMP and emit include/boot_logo_embedded.h (RGB565 PROGMEM).

Usage: python tools/embed_boot_logo.py [path/to/boot_logo.bmp]

Default input: assets/boot_logo.bmp
Requires: BMP with 24 bpp, no compression (BI_RGB).
"""

from __future__ import annotations

import os
import struct
import sys


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def read_bmp_24(path: str) -> tuple[int, int, list[int]]:
    with open(path, "rb") as f:
        hdr = f.read(14)
        if len(hdr) < 14 or hdr[0:2] != b"BM":
            raise SystemExit("Not a BMP file")
        off = struct.unpack_from("<I", hdr, 10)[0]
        dib = f.read(40)
        if len(dib) < 40:
            raise SystemExit("Bad DIB header")
        _bi_size, w, h, planes, bpp = struct.unpack_from("<IiiHH", dib, 0)
        comp = struct.unpack_from("<I", dib, 16)[0]
        if planes != 1 or bpp != 24 or comp != 0:
            raise SystemExit(f"Need 24-bit uncompressed BMP, got bpp={bpp} comp={comp}")
        if h < 0:
            h = -h
            top_down = True
        else:
            top_down = False
        f.seek(off)
        row_pad = (4 - ((w * 3) % 4)) % 4
        out: list[int] = [0] * (w * h)
        rows = []
        for _ in range(h):
            row = f.read(w * 3 + row_pad)
            if len(row) < w * 3 + row_pad:
                raise SystemExit("Unexpected EOF in BMP data")
            rows.append(row[: w * 3])
        if not top_down:
            rows.reverse()
        for y in range(h):
            row = rows[y]
            for x in range(w):
                b, g, r = row[x * 3 : x * 3 + 3]
                out[y * w + x] = rgb888_to_rgb565(r, g, b)
        return w, h, out


def downscale_rgb565_if_needed(
    w: int, h: int, pixels: list[int], max_dim: int
) -> tuple[int, int, list[int]]:
    """Fit inside max_dim×max_dim (aspect preserved) to keep flash size reasonable."""
    if max(w, h) <= max_dim:
        return w, h, pixels
    if w >= h:
        nw = max_dim
        nh = max(1, int(round(h * max_dim / w)))
    else:
        nh = max_dim
        nw = max(1, int(round(w * max_dim / h)))
    out: list[int] = [0] * (nw * nh)
    for y in range(nh):
        sy = (y * (h - 1)) // (nh - 1) if nh > 1 else 0
        for x in range(nw):
            sx = (x * (w - 1)) // (nw - 1) if nw > 1 else 0
            out[y * nw + x] = pixels[sy * w + sx]
    return nw, nh, out


def write_header(out_path: str, w: int, h: int, pixels: list[int]) -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    full = os.path.join(root, out_path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Auto-generated by tools/embed_boot_logo.py — do not edit manually. */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define BOOT_LOGO_W {w}\n")
        f.write(f"#define BOOT_LOGO_H {h}\n\n")
        f.write("static const uint16_t kBootLogoRgb565[] PROGMEM = {\n")
        for i, p in enumerate(pixels):
            if i % 12 == 0:
                f.write("  ")
            f.write(f"0x{p:04X}")
            if i + 1 < len(pixels):
                f.write(",")
            if i % 12 == 11 or i + 1 == len(pixels):
                f.write("\n")
            else:
                f.write(" ")
        f.write("};\n")


def write_placeholder_bmp(path: str, w: int, h: int) -> None:
    """Write a simple 24-bit BI_RGB BMP (bottom-up rows, padded to 4 bytes)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    row_pad = (4 - ((w * 3) % 4)) % 4
    row_size = w * 3 + row_pad
    pixel_size = row_size * h
    off_bits = 14 + 40
    file_size = off_bits + pixel_size
    with open(path, "wb") as f:
        f.write(struct.pack("<2sIHHI", b"BM", file_size, 0, 0, off_bits))
        f.write(
            struct.pack(
                "<IiiHHIIIIII",
                40,
                w,
                h,
                1,
                24,
                0,
                pixel_size,
                0,
                0,
                0,
                0,
            )
        )
        for y in range(h):
            for x in range(w):
                # Dark panel + subtle grid (replace with your art in assets/boot_logo.bmp)
                r = 12 + (x * 3) % 40
                g = 18 + (y * 2) % 30
                b = 28 + ((x + y) * 2) % 50
                f.write(bytes([b, g, r]))
            f.write(b"\x00" * row_pad)


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    default = os.path.join(root, "assets", "boot_logo.bmp")
    if len(sys.argv) > 1 and sys.argv[1] in ("--placeholder", "-p"):
        write_placeholder_bmp(default, 120, 120)
        print(f"Wrote placeholder {default} — replace with your exported BMP and re-run without --placeholder")
        in_path = default
    else:
        in_path = sys.argv[1] if len(sys.argv) > 1 else default
    if not os.path.isfile(in_path):
        raise SystemExit(
            f"Missing {in_path}\n"
            "Export your logo as 24-bit BMP (no compression), or run:\n"
            "  python tools/embed_boot_logo.py --placeholder"
        )
    w0, h0, pix = read_bmp_24(in_path)
    w, h, pix = downscale_rgb565_if_needed(w0, h0, pix, 480)
    if (w, h) != (w0, h0):
        print(f"Scaled logo from {w0}x{h0} to {w}x{h} (max 480px for firmware).")
    out_rel = os.path.join("include", "boot_logo_embedded.h")
    write_header(out_rel, w, h, pix)
    print(f"Wrote {out_rel} ({w}x{h}, {len(pix)} pixels)")


if __name__ == "__main__":
    main()
