#include "ReportGenerator.h"
#include "Standards.h"
#include <LittleFS.h>
#include <Arduino.h>
#include <stdio.h>
#include <string.h>

#define MAX_RESULTS 24
#define BASENAME_LEN 48
#define ROW_LEN 128

struct Row {
  char name[32];
  char value[24];
  char unit[16];
  bool passed;
  char clause[24];
};

static struct {
  bool active;
  char basename[BASENAME_LEN];
  int count;
  Row rows[MAX_RESULTS];
} s_report;

static bool s_fs_ok = false;

bool ReportGenerator_init(void) {
  if (s_fs_ok) return true;
  s_fs_ok = LittleFS.begin(true);
  return s_fs_ok;
}

static void makeBasename(char* out, unsigned cap) {
  unsigned long t = millis() / 1000;
  snprintf(out, cap, "Job_%lu", t);
}

bool ReportGenerator_begin(const char* job_id_or_null) {
  if (!s_fs_ok && !ReportGenerator_init()) return false;
  s_report.active = true;
  s_report.count = 0;
  if (job_id_or_null && job_id_or_null[0])
    strncpy(s_report.basename, job_id_or_null, BASENAME_LEN - 1);
  else
    makeBasename(s_report.basename, BASENAME_LEN);
  s_report.basename[BASENAME_LEN - 1] = '\0';
  return true;
}

void ReportGenerator_addResult(const char* name, const char* value, const char* unit, bool passed, const char* clause) {
  if (!s_report.active || s_report.count >= MAX_RESULTS) return;
  Row* r = &s_report.rows[s_report.count++];
  strncpy(r->name, name ? name : "", sizeof(r->name) - 1);
  r->name[sizeof(r->name) - 1] = '\0';
  strncpy(r->value, value ? value : "", sizeof(r->value) - 1);
  r->value[sizeof(r->value) - 1] = '\0';
  strncpy(r->unit, unit ? unit : "", sizeof(r->unit) - 1);
  r->unit[sizeof(r->unit) - 1] = '\0';
  r->passed = passed;
  strncpy(r->clause, clause ? clause : "", sizeof(r->clause) - 1);
  r->clause[sizeof(r->clause) - 1] = '\0';
}

static bool writeFile(const char* path, const char* content) {
  File f = LittleFS.open(path, "w");
  if (!f) return false;
  size_t n = strlen(content);
  if (f.write((const uint8_t*)content, n) != n) { f.close(); return false; }
  f.close();
  return true;
}

bool ReportGenerator_end(void) {
  if (!s_report.active) return false;

  char path[64];
  char rules_ver[16];
  Standards_getRulesVersion(rules_ver, sizeof(rules_ver));

  /* CSV */
  String csv = "Test,Value,Unit,Result,Clause\r\n";
  for (int i = 0; i < s_report.count; i++) {
    Row* r = &s_report.rows[i];
    csv += String(r->name) + "," + r->value + "," + r->unit + "," + (r->passed ? "PASS" : "FAIL") + "," + r->clause + "\r\n";
  }
  snprintf(path, sizeof(path), "/reports/%s.csv", s_report.basename);
  if (!writeFile(path, csv.c_str())) { s_report.active = false; return false; }

  /* HTML */
  String html = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><title>SparkyCheck Report</title>";
  html += "<style>body{font-family:sans-serif;margin:1rem;} table{border-collapse:collapse;} th,td{border:1px solid #333;padding:6px 10px;} .pass{background:#cfc;} .fail{background:#fcc;}</style></head><body>";
  html += "<h1>SparkyCheck Verification Report</h1>";
  html += "<p><strong>Job:</strong> " + String(s_report.basename) + " &nbsp; <strong>Rules:</strong> " + String(rules_ver) + "</p>";
  html += "<table><tr><th>Test</th><th>Value</th><th>Unit</th><th>Result</th><th>Clause</th></tr>";
  for (int i = 0; i < s_report.count; i++) {
    Row* r = &s_report.rows[i];
    html += "<tr class=\"" + String(r->passed ? "pass" : "fail") + "\"><td>" + r->name + "</td><td>" + r->value + "</td><td>" + r->unit + "</td><td>" + (r->passed ? "PASS" : "FAIL") + "</td><td>" + r->clause + "</td></tr>";
  }
  html += "</table><p><em>Generated by SparkyCheck. AS/NZS 3000, 3017, 3760 as applicable.</em></p></body></html>";
  snprintf(path, sizeof(path), "/reports/%s.html", s_report.basename);
  if (!writeFile(path, html.c_str())) { s_report.active = false; return false; }

  s_report.active = false;
  return true;
}

void ReportGenerator_getLastBasename(char* buf, unsigned buf_size) {
  if (buf_size) buf[0] = '\0';
  strncpy(buf, s_report.basename, buf_size - 1);
  if (buf_size) buf[buf_size - 1] = '\0';
}

int ReportGenerator_listReports(char* buf, unsigned buf_size) {
  if (!s_fs_ok || !buf || buf_size < 2) return 0;
  buf[0] = '\0';
  File root = LittleFS.open("/reports");
  if (!root || !root.isDirectory()) return 0;
  int n = 0;
  File f = root.openNextFile();
  while (f && n < 32) {
    String name = f.name();
    if (name.endsWith(".html")) {
      name.remove(name.length() - 5);
      if (strlen(buf) + name.length() + 2 < buf_size) {
        if (n) strcat(buf, "\n");
        strcat(buf, name.c_str());
        n++;
      }
    }
    f = root.openNextFile();
  }
  return n;
}
